version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opi_web_1
      APP_PORT: 3000

  web:
    image: getumbrel/opi:1.0.0
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - BITCOIN_RPC_HOST=${APP_BITCOIN_NODE_IP}
      - BITCOIN_RPC_PORT=${APP_BITCOIN_RPC_PORT}
      - BITCOIN_RPC_USER=${APP_BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASS=${APP_BITCOIN_RPC_PASS}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${APP_SEED}
      - POSTGRES_DB=opi    volumes:
      - opi_data:/data
      - ${APP_BITCOIN_DATA_DIR}:/bitcoin:ro
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${APP_SEED}
      - POSTGRES_DB=opi    volumes:
      - opi_postgres:/var/lib/postgresql/data

volumes:
  opi_data:
    name: "${VOLUME_PREFIX:-opi}_data"
  opi_postgres:
    name: "${VOLUME_PREFIX:-opi}_postgres"

networks:
  default:
    driver: bridge
  bitcoin:
    external: true
    name: "${BITCOIN_NETWORK:-umbrel_bitcoin_default}"
